services:
  - type: web
    name: audio-converter-bot
    env: docker
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PORT
        value: 8080
      - key: FORCE_SUB_CHANNEL
        value: "@DARK_RIFT_ZONE" 
        # Yahan apne channel ka username likho (e.g. @MoviesHub)
        # Note: Bot ko is channel ka ADMIN banana zaroori hai!
