services:
  - type: web
    name: audio-converter-bot
    env: python
    buildCommand: |-
      pip install --upgrade pip
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
