services:
  - type: web
    name: audio-converter-bot
    env: docker
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PORT
        value: 8080
      - key: FORCE_SUB_CHANNEL
        value: "" 
        # Enter your channel username starting with @ (e.g. @my_updates)
        # Leave empty to disable verification.